export const previewPrompts = [
  {
    id: 'preview-brand-campaign',
    title: '品牌上市活動提示詞',
    slug: 'brand-launch-campaign',
    summary: '產出社群貼文、廣告標題與 Landing Page 文案的完整提示詞套件。',
    engine: 'text',
    model: 'gpt-4.1',
    status: 'published',
    priceCredits: 0,
    viewCount: 1280,
    saveCount: 236,
    owner: { username: 'promptforge', avatarUrl: null },
  },
  {
    id: 'preview-product-photo',
    title: '商品攝影圖像提示詞',
    slug: 'product-photo-prompt',
    summary: '適合飲品、保養品與生活用品的高質感商攝風格圖像提示詞。',
    engine: 'image',
    model: 'gpt-image',
    status: 'marketplace',
    priceCredits: 12,
    viewCount: 960,
    saveCount: 184,
    owner: { username: 'visualsmith', avatarUrl: null },
  },
  {
    id: 'preview-character-design',
    title: '角色設計 Prompt Blueprint',
    slug: 'character-design-blueprint',
    summary: '角色外觀、服裝、世界觀與一致性描述的多段式提示詞。',
    engine: 'image',
    model: 'stable-diffusion',
    status: 'published',
    priceCredits: 8,
    viewCount: 740,
    saveCount: 142,
    owner: { username: 'characterlab', avatarUrl: null },
  },
];

export const previewMarketplaceItems = previewPrompts.map((prompt, index) => ({
  id: `market-${prompt.id}`,
  prompt,
  seller: prompt.owner,
  priceCredits: prompt.priceCredits || 6 + index * 3,
  ratingAvg: 4.6 + index * 0.1,
  salesCount: 80 + index * 42,
  license: index === 0 ? 'free' : 'commercial',
}));
